### ISSUE TITLE
Debug logging does not work on DEV

### ISSUE THREAD

**Issue by dsmf** [eclipse-tractusx/item-relationship-service#396]
## Description

During testing #214 on DEV we noticed that log messages with level DEBUG do not appear in the logs (except for the CompositeLog)  even though this should be the case. 

This story is related to #293. 

## Current behaviour

Log level DEBUG is not logged.

## Expected behavior

Log level DEBUG is logged.

## Steps to reproduce the Bug

Run a query that executes code which has some logging with level DEBUG.

**Comment by ds-jhartmann** [comment]
Might be related to `irs-api/src/main/resources/application.yml`:
```
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: WARN
    org.springframework: INFO
    org.eclipse.tractusx.irs: INFO
```
